name: flex-pse-examples
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      - flex-pse[solvers, dev] @ git+https://github.com/flex-pse/flexPSE.git@main
      - marimo
      - duckdb
      - matplotlib
